version: '3'
services: 
    database:
        image: 'mongo'
        container_name: 'database'
        environment: 
            MONGO_INITDB_DATABASE: products
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: products
        volumes:
            - ./mongo-volume:/data/db
        ports:
            - '27017-27019:27017-27019'
    es7:
        container_name: products-container-es7
        build: docker/elasticsearch7/
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./docker/elasticsearch7/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        ports:
            - '9200:9200'
            - '9300:9300'
        environment:
            - discovery.type=single-node
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xmx512m -Xms512m"